{{- if .Values.secretsManager.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "api-redis-stack.fullname" . }}-redis-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "api-redis-stack.labels" . | nindent 4 }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .Values.secretsManager.secretName }}"
        objectType: "secretsmanager"
        jmesPath:
          - path: "password"
            objectAlias: "redis-password"
  secretObjects:
    - secretName: {{ include "api-redis-stack.fullname" . }}-redis-secret
      type: Opaque
      data:
        - objectName: "redis-password"
          key: "password"
{{- end }}
