apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "api-redis-stack.serviceAccountName" . }}
  labels:
    {{- include "api-redis-stack.labels" . | nindent 4 }}
  {{- with .Values.api.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
