apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "api-redis-stack.serviceAccountName" . }}
  labels:
    {{- include "api-redis-stack.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.api.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.irsa.enabled }}
    eks.amazonaws.com/role-arn: {{ .Values.irsa.roleArn }}
    {{- end }}
automountServiceAccountToken: true
